### PR TITLE
Analysis  of Temperature Rise in PMSM. 

### PR DESCRIPTION
**Pull request by Shivani-Khare**
This file contains a detailed analysis of factors leading to temperature rise in Permanent Magnet Synchronous Motors (PMSM). The file aims at analyzing the factors which contribute to the demagnetization of permanent magnets present as the rotor of the machine leading to temperature rise in the machine parts resulting in decreased efficiency. This file also contains a detailed HTML report on the dataset used in the analysis of the temperature rise of PMSM.

### CODE REVIEW

**Comment by Shivani-Khare** [comment]
Please review my project - Analysis of Temperature Rise in PMSM. Issue number - #123

**Comment by Niketkumardheeryan** [comment]
@Shivani-Khare add readme.md file

**Comment by Shivani-Khare** [comment]
> @Shivani-Khare add readme.md file

Okay sure. I will do it.

**Comment by Shivani-Khare** [comment]
@Niketkumardheeryan I have added the readme.md file. 

The project belongs to the issue #174 that was created by me.

**Pull request merged**
