### PR TITLE
python of basic

### PR DESCRIPTION
**Pull request by SurajPawar15-smart**
Sir, please check this and some part of ml is remaining,I will push within 2 or 4 days with ml code and datasets.

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@SurajPawar15-smart add more & u will get max. level tag

**Comment by SurajPawar15-smart** [comment]
sir, please view my folder and give me your feedback.

**Comment by SurajPawar15-smart** [comment]
now changes is done ,i added 2 projects  and some basic ml model with codes (datasets)

**Comment by SurajPawar15-smart** [comment]
Thank u so much sir🙏🙏

**Pull request merged**
