### PR TITLE
Flight delay prediction

### LINKED ISSUE #22: Flight Delay prediction
Can i Add jupyter notebook for the flight delay prediction for the dataset available on kaggel . with proper comments about the python library used. 
I am LGMSOC participant 
https://www.kaggle.com/usdot/flight-delays

### PR DESCRIPTION
**Pull request by Komal-99**
fixes #22 
I have added the drive link for the dataset as the file is more than 25mb and could not be uploaded on git

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@Komal-99 there is no readme.md file for this project , add readme.md file and attach the link of dataset into it, 

in .pynb file add comments or markdowns,

**Comment by Komal-99** [comment]
> @Komal-99 there is no readme.md file for this project , add readme.md file and attach the link of dataset into it,
> 
> in .pynb file add comments or markdowns,

**Comment by Komal-99** [comment]
kindly check!!

**Review by omagrawal1111 — APPROVED** [review]

**Comment by Komal-99** [comment]
Thanks for approving, please  add LGMSOC'21 label and difficulty level  lab

**Comment by Niketkumardheeryan** [comment]
@Komal-99 watch a video on youtube ,how to make readme.md file, or improve your readme.md file ,

**Comment by Komal-99** [comment]
> @Komal-99 watch a video on youtube ,how to make readme.md file, or improve your readme.md file ,

ok

**Comment by Komal-99** [comment]
> @Komal-99 watch a video on youtube ,how to make readme.md file, or improve your readme.md file ,

Kindly check new commit

**Pull request merged**
