### PR TITLE
Modify Readme

### LINKED ISSUE #6: Make the more attractive Readme.md file for this repo

### PR DESCRIPTION
**Pull request by Komal-99**
fixes #6

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@Komal-99 need more improvements, u can take help from other readme.md files .

**Comment by Komal-99** [comment]
Actually  i want to do more but in project their is no contributing guidelines file made which i can add here also , I am not aware of any license if project have . And a lot can be added but ut depends on project so if you can tell key heading of what to add  , for bow i just edited  headings which  was their already.

**Comment by Niketkumardheeryan** [comment]
@Komal-99 take a look into readme.md file of  this repo -https://github.com/ashishsahu1/ML-ProjectYard

and for headings - you can take help  from "Applied ai" (visit their website) syllabus,  

in simple words- our aim is to make a repo that can be useful for a Data Analyst, Data scientist ,

**Comment by Komal-99** [comment]
Okay

**Comment by Komal-99** [comment]
Can you make contributing guidelines and contributors.md for name of contributor so that I can include it

**Comment by Niketkumardheeryan** [comment]
@Komal-99 I will give it to u by tomorrow

**Comment by Komal-99** [comment]
So what about repo link do you want all repository link in readme?

**Comment by Niketkumardheeryan** [comment]
similar to it - https://github.com/github/docs/blob/main/CONTRIBUTING.md , change according to this repo

**Comment by Komal-99** [comment]
So shall i make new issue for Adding contributing guidelines @Niketkumardheeryan  as it is seperate file which will be further linked to readme

**Comment by Komal-99** [comment]
@Niketkumardheeryan  I have done all the changes Which can be added to Readme.md hope you like it

**Pull request merged**
