### PR TITLE
Added 2 files

### PR DESCRIPTION
**Pull request by Megha0606**
Please Review my PR 
I have added both the files

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@Megha0606 add   .ipynb files  not .py

**Comment by Megha0606** [comment]
Okay I'll make changes and upload again

**Comment by Megha0606** [comment]
Please Review my PR

**Comment by Niketkumardheeryan** [comment]
@Megha0606 ur files are mot loading ,,,

**Comment by Niketkumardheeryan** [comment]
reupload it.

**Comment by Megha0606** [comment]
Okay I'll do

**Pull request closed without merging**
