### PR TITLE
Handwritten Equation Solver using CNN

### PR DESCRIPTION
**Pull request by shivani6320**
## Related Issue 
- The project's aim is to solve handwritten equations using CNN model.

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #62 

### Describe the changes you've made

I have created a CNN model to recognize handwritten digits and then evaluate the equation and predict correct answer.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
- The accuracy of CNN model is 98.2 %

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@shivani6320 explain work flow of ur project in readme.md file, step by step approach...

**Comment by shivani6320** [comment]
@Niketkumardheeryan Changes has been made. please check :)

**Comment by Niketkumardheeryan** [comment]
@shivani6320 simply copy, paste project,,,, Add comments in your code

**Comment by shivani6320** [comment]
I have commented the code. Please check.

**Pull request merged**
