### PR TITLE
Improve Readme.md file 

### PR DESCRIPTION
**Pull request by Akash20x**
Closes issue: #120 

I improve readme.md file a little bit and also add github actions with a python script to automate the main contents of repo to display in readme.md with their link.

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@Akash20x use grid for storing content ....

**Comment by Akash20x** [comment]
> @Akash20x use grid for storing content ....

Where I didn't understand, please elaborate

**Comment by Akash20x** [comment]
> @Akash20x use grid for storing content ....

@Niketkumardheeryan Did you mean that I have to display contents in tabular form.

**Comment by Niketkumardheeryan** [comment]
@Akash20x yep, got it right..

**Comment by Akash20x** [comment]
> @Akash20x yep, got it right..

OK I will do it

**Comment by Akash20x** [comment]
@Niketkumardheeryan I have done the required changes, please check it

**Comment by Niketkumardheeryan** [comment]
@Akash20x hey u have added content list manually ,u have to automate this step, if a new project will be added into this repo,it should be automatically add into that list.

**Comment by Niketkumardheeryan** [comment]
add contributors  at last too.

**Comment by Akash20x** [comment]
> @Akash20x hey u have added content list manually ,u have to automate this step, if a new project will be added into this repo,it should be automatically add into that list.

No it is not manually,
Try delete contents and then check it will automatically come after 1 minute.

**Comment by Akash20x** [comment]
> add contributors at last too.

OK

**Comment by Akash20x** [comment]
@Niketkumardheeryan I have done the required changes,please check my pull request.

**Pull request merged**
